modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="abyss"
version="2.2.2"
displayName="Abyss"
displayURL="https://modrinth.com/mod/deepabyss"
logoFile="logo.png"
credits="fish"
authors="Prodigy"
description="Simply adds a deep ocean"

[[dependencies.abyss]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.abyss]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.abyss]]
    modId="create_submarine"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.abyss]]
    modId="fusion"
    type="optional"
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="CLIENT"
