modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="abyss"
version="1.2.0"
displayName="Abyss"
displayURL="https://modrinth.com/mod/deepseasabyss"
logoFile="logo.png"
credits="fish"
authors="Prodigy"
description="Simply adds a deep ocean"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.abyss]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.abyss]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration